export const departments = [
  {
    id: 1,
    facultyID: 1,
    name: 'Agricultural Economics',
    value: 'Agricultural Economics',
  },
  {
    id: 2,
    facultyID: 1,
    name: 'Agricultural Extension & Rural Development',
    value: 'Agricultural Extension & Rural Development',
  },
  {
    id: 3,
    facultyID: 1,
    name: 'Animal Science',
    value: 'Animal Science',
  },
  {
    id: 4,
    facultyID: 1,
    name: 'Crop Protection & Environmental Biology',
    value: 'Crop Protection & Environmental Biology',
  },
  {
    id: 5,
    facultyID: 1,
    name: 'Soil Resources Management',
    value: 'Soil Resources Management',
  },
  {
    id: 6,
    facultyID: 1,
    name: 'Crop Horticulture',
    value: 'Crop Horticulture',
  },
  {
    id: 7,
    facultyID: 2,
    name: 'Arabic & Islamic Studies',
    value: 'Arabic & Islamic Studies',
  },
  {
    id: 8,
    facultyID: 2,
    name: 'Classics',
    value: 'Classics',
  },
  {
    id: 9,
    facultyID: 2,
    name: 'Communications & Language Arts',
    value: 'Communications & Language Arts',
  },
  {
    id: 10,
    facultyID: 2,
    name: 'English',
    value: 'English',
  },
  {
    id: 11,
    facultyID: 2,
    name: 'European Studies',
    value: 'European Studies',
  },
  {
    id: 12,
    facultyID: 2,
    name: 'History',
    value: 'History',
  },
  {
    id: 13,
    facultyID: 2,
    name: 'Linguistics & African Languages',
    value: 'Linguistics & African Languages',
  },
  {
    id: 14,
    facultyID: 2,
    name: 'Music',
    value: 'Music',
  },
  {
    id: 15,
    facultyID: 2,
    name: 'Philosophy',
    value: 'Philosophy',
  },
  {
    id: 16,
    facultyID: 2,
    name: 'Religious Studies',
    value: 'Religious Studies',
  },
  {
    id: 17,
    facultyID: 2,
    name: 'Theatre Arts',
    value: 'Theatre Arts',
  },
  {
    id: 18,
    facultyID: 3,
    name: 'Biochemistry',
    value: 'Biochemistry',
  },
  {
    id: 19,
    facultyID: 3,
    name: 'Chemical Pathology',
    value: 'Chemical Pathology',
  },
  {
    id: 20,
    facultyID: 3,
    name: 'Haematology',
    value: 'Haematology',
  },
  {
    id: 21,
    facultyID: 3,
    name: 'Medical Microbiology & Parasitology',
    value: 'Medical Microbiology & Parasitology',
  },
  {
    id: 22,
    facultyID: 3,
    name: 'Pathology',
    value: 'Pathology',
  },
  {
    id: 23,
    facultyID: 3,
    name: 'Pharmacology & Therapeutics',
    value: 'Pharmacology & Therapeutics',
  },
  {
    id: 24,
    facultyID: 3,
    name: 'Physiology',
    value: 'Physiology',
  },
  {
    id: 25,
    facultyID: 3,
    name: 'Virology',
    value: 'Virology',
  },
  {
    id: 26,
    facultyID: 3,
    name: 'Biomedical Lab Science',
    value: 'Biomedical Lab Science',
  },
  {
    id: 27,
    facultyID: 3,
    name: 'Immunology',
    value: 'Immunology',
  },
  {
    id: 28,
    facultyID: 3,
    name: 'Anatomy',
    value: 'Anatomy',
  },
  {
    id: 29,
    facultyID: 4,
    name: 'Anaesthesia',
    value: 'Anaesthesia',
  },
  {
    id: 30,
    facultyID: 4,
    name: 'Medicine',
    value: 'Medicine',
  },
  {
    id: 31,
    facultyID: 4,
    name: 'Nursing',
    value: 'Nursing',
  },
  {
    id: 32,
    facultyID: 4,
    name: 'Obstetrics & Gynaecology',
    value: 'Obstetrics & Gynaecology',
  },
  {
    id: 33,
    facultyID: 4,
    name: 'Ophthalmology',
    value: 'Ophthalmology',
  },
  {
    id: 34,
    facultyID: 4,
    name: 'Oto-Rhino-Laryngology',
    value: 'Oto-Rhino-Laryngology',
  },
  {
    id: 35,
    facultyID: 4,
    name: 'Radiology ',
    value: 'Radiology ',
  },
  {
    id: 36,
    facultyID: 4,
    name: 'Radiotherapy Radiation Oncology',
    value: 'Radiotherapy Radiation Oncology',
  },
  {
    id: 37,
    facultyID: 4,
    name: 'Paediatrics',
    value: 'Paediatrics',
  },
  {
    id: 38,
    facultyID: 4,
    name: 'Physiotherapy',
    value: 'Physiotherapy',
  },
  {
    id: 39,
    facultyID: 4,
    name: 'Psychiatry',
    value: 'Psychiatry',
  },
  {
    id: 40,
    facultyID: 4,
    name: 'Surgery',
    value: 'Surgery',
  },
  {
    id: 41,
    facultyID: 4,
    name: 'Nuclear Medicine',
    value: 'Nuclear Medicine',
  },
  {
    id: 42,
    facultyID: 5,
    name: 'Child Oral Health',
    value: 'Child Oral Health',
  },
  {
    id: 43,
    facultyID: 5,
    name: 'Oral & Maxillofacial Surgery',
    value: 'Oral & Maxillofacial Surgery',
  },
  {
    id: 44,
    facultyID: 5,
    name: 'Oral Pathology/Oral Medicine',
    value: 'Oral Pathology/Oral Medicine',
  },
  {
    id: 45,
    facultyID: 5,
    name: 'Peridontology & Comm. Dentistry',
    value: 'Peridontology & Comm. Dentistry',
  },
  {
    id: 46,
    facultyID: 5,
    name: 'Restorative Dentistry',
    value: 'Restorative Dentistry',
  },
  {
    id: 47,
    facultyID: 6,
    name: 'Accounting',
    value: 'Accounting',
  },
  {
    id: 48,
    facultyID: 6,
    name: 'Business Administration',
    value: 'Business Administration',
  },
  {
    id: 49,
    facultyID: 6,
    name: 'Marketing and Consumer Studies',
    value: 'Marketing and Consumer Studies',
  },
  {
    id: 50,
    facultyID: 6,
    name: 'Banking and Finance',
    value: 'Banking and Finance',
  },
  {
    id: 51,
    facultyID: 6,
    name: 'Economics',
    value: 'Economics',
  },
  {
    id: 52,
    facultyID: 7,
    name: 'Adult Education',
    value: 'Adult Education',
  },
  {
    id: 53,
    facultyID: 7,
    name: 'Educational Management',
    value: 'Educational Management',
  },
  {
    id: 54,
    facultyID: 7,
    name: 'Counselling and Human Development Studies',
    value: 'Counselling and Human Development Studies',
  },
  {
    id: 55,
    facultyID: 7,
    name: 'Human Kinetic & Health Education',
    value: 'Human Kinetic & Health Education',
  },
  {
    id: 56,
    facultyID: 7,
    name: 'Library Archival & Information Sciences',
    value: 'Library Archival & Information Sciences',
  },
  {
    id: 57,
    facultyID: 7,
    name: 'Social Work',
    value: 'Social Work',
  },
  {
    id: 58,
    facultyID: 7,
    name: 'Special Education',
    value: 'Special Education',
  },
  {
    id: 59,
    facultyID: 7,
    name: 'Arts & Social Sciences Education',
    value: 'Arts & Social Sciences Education',
  },
  {
    id: 60,
    facultyID: 7,
    name: 'Childhood and Educational Foundation',
    value: 'Childhood and Educational Foundation',
  },
  {
    id: 61,
    facultyID: 7,
    name: 'Science, Mathematics & Technology Education',
    value: 'Science, Mathematics & Technology Education',
  },
  {
    id: 62,
    facultyID: 8,
    name: 'Urban and Regional Planning',
    value: 'Urban and Regional Planning',
  },
  {
    id: 63,
    facultyID: 8,
    name: 'Estate Management',
    value: 'Estate Management',
  },
  {
    id: 64,
    facultyID: 8,
    name: 'Quantity Surveying',
    value: 'Quantity Surveying',
  },
  {
    id: 65,
    facultyID: 8,
    name: 'Architecture',
    value: 'Architecture',
  },
  {
    id: 66,
    facultyID: 9,
    name: 'Commercial and Industrial Law',
    value: 'Commercial and Industrial Law',
  },
  {
    id: 67,
    facultyID: 9,
    name: 'Jurisprudence and International Law',
    value: 'Jurisprudence and International Law',
  },
  {
    id: 68,
    facultyID: 9,
    name: 'Private & Property Law',
    value: 'Private & Property Law',
  },
  {
    id: 69,
    facultyID: 9,
    name: 'Public Law',
    value: 'Public Law',
  },
  {
    id: 70,
    facultyID: 10,
    name: 'Clinical Pharmacy & Pharmacy Administration',
    value: 'Clinical Pharmacy & Pharmacy Administration',
  },
  {
    id: 71,
    facultyID: 10,
    name: 'Pharmacognosy',
    value: 'Pharmacognosy',
  },
  {
    id: 72,
    facultyID: 10,
    name: 'Pharmaceutical Chemistry',
    value: 'Pharmaceutical Chemistry',
  },
  {
    id: 73,
    facultyID: 10,
    name: 'Pharmaceutics & Industrial Pharmacy',
    value: 'Pharmaceutics & Industrial Pharmacy',
  },
  {
    id: 74,
    facultyID: 10,
    name: 'Pharmaceutical Microbiology',
    value: 'Pharmaceutical Microbiology',
  },
  {
    id: 75,
    facultyID: 10,
    name: 'Pharmacology & Toxicology',
    value: 'Pharmacology & Toxicology',
  },
  {
    id: 76,
    facultyID: 11,
    name: 'Environmental Health Sciences',
    value: 'Environmental Health Sciences',
  },
  {
    id: 77,
    facultyID: 11,
    name: 'Epidemiology & Medical Statistics',
    value: 'Epidemiology & Medical Statistics',
  },
  {
    id: 78,
    facultyID: 11,
    name: 'Health Promotion & Education',
    value: 'Health Promotion & Education',
  },
  {
    id: 79,
    facultyID: 11,
    name: 'Human Nutrition',
    value: 'Human Nutrition',
  },
  {
    id: 80,
    facultyID: 11,
    name: 'Preventive Medicine & Primary Health Care',
    value: 'Preventive Medicine & Primary Health Care',
  },
  {
    id: 81,
    facultyID: 11,
    name: 'Health Policy and Management',
    value: 'Health Policy and Management',
  },
  {
    id: 82,
    facultyID: 11,
    name: 'Community Medicine',
    value: 'Community Medicine',
  },
  {
    id: 83,
    facultyID: 12,
    name: 'Aquaculture & Fisheries Management',
    value: 'Aquaculture & Fisheries Management',
  },
  {
    id: 84,
    facultyID: 12,
    name: 'Social and Environmental Forestry',
    value: 'Social and Environmental Forestry',
  },
  {
    id: 85,
    facultyID: 12,
    name: 'Forest Production and Products',
    value: 'Forest Production and Products',
  },
  {
    id: 86,
    facultyID: 12,
    name: 'Wildlife & Ecotourism Management',
    value: 'Wildlife & Ecotourism Management',
  },
  {
    id: 87,
    facultyID: 13,
    name: 'Archaeology & Anthropology',
    value: 'Archaeology & Anthropology',
  },
  {
    id: 88,
    facultyID: 13,
    name: 'Botany',
    value: 'Botany',
  },
  {
    id: 89,
    facultyID: 13,
    name: 'Chemistry',
    value: 'Chemistry',
  },
  {
    id: 90,
    facultyID: 13,
    name: 'Computer Science',
    value: 'Computer Science',
  },
  {
    id: 91,
    facultyID: 13,
    name: 'Geology',
    value: 'Geology',
  },
  {
    id: 92,
    facultyID: 13,
    name: 'Mathematics',
    value: 'Mathematics',
  },
  {
    id: 93,
    facultyID: 13,
    name: 'Microbiology',
    value: 'Microbiology',
  },
  {
    id: 94,
    facultyID: 13,
    name: 'Physics',
    value: 'Physics',
  },
  {
    id: 95,
    facultyID: 13,
    name: 'Statistics',
    value: 'Statistics',
  },
  {
    id: 96,
    facultyID: 13,
    name: 'Zoology',
    value: 'Zoology',
  },
  {
    id: 97,
    facultyID: 14,
    name: 'Agricultural  & Environmental Engineering',
    value: 'Agricultural  & Environmental Engineering',
  },
  {
    id: 98,
    facultyID: 14,
    name: 'Civil Engineering',
    value: 'Civil Engineering',
  },
  {
    id: 99,
    facultyID: 14,
    name: 'Electrical & Electronic Engineering',
    value: 'Electrical & Electronic Engineering',
  },
  {
    id: 100,
    facultyID: 14,
    name: 'Food Technology',
    value: 'Food Technology',
  },
  {
    id: 101,
    facultyID: 14,
    name: 'Industrial & Production Engineering',
    value: 'Industrial & Production Engineering',
  },
  {
    id: 102,
    facultyID: 14,
    name: 'Mechanical Engineering',
    value: 'Mechanical Engineering',
  },
  {
    id: 103,
    facultyID: 14,
    name: 'Petroleum Engineering',
    value: 'Petroleum Engineering',
  },
  {
    id: 104,
    facultyID: 14,
    name: 'Wood Products Engineering',
    value: 'Wood Products Engineering',
  },
  {
    id: 105,
    facultyID: 14,
    name: 'Biomedical Engineering',
    value: 'Biomedical Engineering',
  },
  {
    id: 106,
    facultyID: 14,
    name: 'Automotive Engineering',
    value: 'Automotive Engineering',
  },
  {
    id: 107,
    facultyID: 15,
    name: 'Geography',
    value: 'Geography',
  },
  {
    id: 108,
    facultyID: 15,
    name: 'Political Science',
    value: 'Political Science',
  },
  {
    id: 109,
    facultyID: 15,
    name: 'Psychology',
    value: 'Psychology',
  },
  {
    id: 110,
    facultyID: 15,
    name: 'Sociology',
    value: 'Sociology',
  },
  {
    id: 111,
    facultyID: 16,
    name: 'Veterinary Anatomy',
    value: 'Veterinary Anatomy',
  },
  {
    id: 112,
    facultyID: 16,
    name: 'Veterinary Medicine',
    value: 'Veterinary Medicine',
  },
  {
    id: 113,
    facultyID: 16,
    name: 'Veterinary Pathology',
    value: 'Veterinary Pathology',
  },
  {
    id: 114,
    facultyID: 16,
    name: 'Veterinary Surgery & Radiology',
    value: 'Veterinary Surgery & Radiology',
  },
  {
    id: 115,
    facultyID: 16,
    name: 'Theriogenology',
    value: 'Theriogenology',
  },
  {
    id: 116,
    facultyID: 16,
    name: 'Veterinary Microbiology ',
    value: 'Veterinary Microbiology ',
  },
  {
    id: 117,
    facultyID: 16,
    name: 'Veterinary Parasitology',
    value: 'Veterinary Parasitology',
  },
  {
    id: 118,
    facultyID: 16,
    name: 'Veterinary Public Health & Preventive Medicin',
    value: 'Veterinary Public Health & Preventive Medicin',
  },
  {
    id: 119,
    facultyID: 16,
    name: 'Veterinary Physiology and Biochemistry ',
    value: 'Veterinary Physiology and Biochemistry ',
  },
  {
    id: 120,
    facultyID: 16,
    name: 'Veterinary  Pharmacology & Toxicology',
    value: 'Veterinary  Pharmacology & Toxicology',
  },
  {
    id: 121,
    facultyID: 16,
    name: 'Veterinary Teaching Hospital',
    value: 'Veterinary Teaching Hospital',
  },
];

export const faculties = [
  {
    id: 1,
    name: 'Faculty of Science',
    value: 'Faculty of Science',
  },
  {
    id: 2,
    name: 'Faculty of Arts',
    value: 'Faculty of Arts',
  },
  {
    id: 3,
    name: 'Faculty of Engineering',
    value: 'Faculty of Engineering',
  },
  {
    id: 4,
    name: 'Faculty of Business',
    value: 'Faculty of Business',
  },
  {
    id: 5,
    name: 'Faculty of Medicine',
    value: 'Faculty of Medicine',
  },
  {
    id: 6,
    name: 'Faculty of Law',
    value: 'Faculty of Law',
  },
  {
    id: 7,
    name: 'Faculty of Education',
    value: 'Faculty of Education',
  },
  {
    id: 8,
    name: 'Faculty of Social Sciences',
    value: 'Faculty of Social Sciences',
  },
  {
    id: 9,
    name: 'Faculty of Fine Arts',
    value: 'Faculty of Fine Arts',
  },
  {
    id: 10,
    name: 'Faculty of Information Technology',
    value: 'Faculty of Information Technology',
  },
];
export const gender = [
  {
    id: 'M',
    value: 'M',
    name: 'male',
  },
  {
    id: 'F',
    value: 'F',
    name: 'female',
  },
];

export const lookupTable = {
  departmentID: {
    name: 'department_odd',
    common: 'departmentName',
    seperateTable: true,
  },
  faculty: { name: 'faculty', common: 'facultyName', seperateTable: true },
  gender: { name: 'gender', common: 'gender', seperateTable: false },
};
